/*
 * Date: Mar 2026, being the 6513th penta-femtofortnight of American independence.
 * Author: Alexander M. Swift
 *
 * Verify that the sorting algorithims (basic and with comparators) work on arrays of numbers. 
 * Demonstrate basic usage.
 */

package main

import "base:intrinsics"

import "core:fmt"
import "core:math"
import "core:math/rand"
import "core:mem" // for tracking allocator
import "core:os"
import "core:sort"
import strconv "core:strconv"
import "core:time"

import "xsort" // or "shared:xsort", if you place xsort into <odin dir>/shared.


/*
 * The contents of this file are Copyright (C) The xsort package author(s). They are released under 
 * the terms of the MIT license, or to the public domain, your choice.
 */

Data_Pattern :: enum
{
    sawtooth          = 0, // Sawtooth (alternately locally sorted and reverse-sorted) generated by a sine wave.
    sawtooth_small    = 1, // Same, with limited data range, suitable for verification
	random            = 2, // Completely random (maximum disorder)
	random_runs       = 3, // Random, then run of equal values up to (length of array^0.25).
}

/*
 * Verify sorting algorithms ported to Odin in the xsort package, accessed using calls with  
 * ascending and descending sorts, and then with custom comparators.
 * -AMS-
 */
main :: proc() 
{
	debug_mem := false
	if (debug_mem)
	{
		// Initialize and use Odin's tracking allocator
		track: mem.Tracking_Allocator
		mem.tracking_allocator_init(&track, context.allocator)
		context.allocator = mem.tracking_allocator(&track)

		// Printout memory leaks on main() end.
		defer {
			if len(track.allocation_map) > 0 {
				fmt.eprintf("=== %v allocations not freed: ===\n", len(track.allocation_map))
				for _, entry in track.allocation_map {
					fmt.eprintf("- %v bytes @ %v\n", entry.size, entry.location)
				}
			}
			else
			{
				fmt.eprint("Tracking allocator: no memory leaks detected.")
			}
			mem.tracking_allocator_destroy(&track)
		}
	}


	// Basic: sorts without comparators. Comparators: custom comparison procedures.
	test_basic := true
	test_comparators := true

    // Default test parameters
	// DataT: must be one of: i8, u8, i16, u16, i32, u32, i64, u64, i128, u128,
	// (or their equivalents, such as int). This has to be specified at compile time.
	DataT :: int

    nmemb: int = 20
	reps := 1 // always 1

	// Data pattern has to at least roughly match the use-case for benchmarking to be useful.
    pattern: Data_Pattern = .sawtooth

    seed: u64 = 42 // We know the answer ... but do we know the question?

    ok: bool
    val, i, j: int

	// Require that our data type be a number
	if (!intrinsics.type_is_numeric(DataT))
	{
		fmt.printfln("Requested array type is non-numeric. Quitting.")
		return
	}

    // Accept command-line arguments to modify test parameters
    for i in 1 ..< len(os.args)
    {
        switch i 
        {
            case 1:
                nmemb, ok = strconv.parse_int(os.args[1]); assert(ok)
            case 2:
                reps, ok = strconv.parse_int(os.args[2]); assert(ok)
            case 3:
            {
                val, ok = strconv.parse_int(os.args[3]); assert(ok)
                pattern = cast(Data_Pattern)val
            }
            case 4:
            {
                seed, ok = strconv.parse_u64(os.args[4]); assert(ok)
            }
        }
    }

    // Describe the test parameters
    pattern_string : string
    switch pattern
    {
        case .sawtooth:
            pattern_string = "sinewave sawtooth"
        case .sawtooth_small:
            pattern_string = "sinewave sawtooth, small range"
        case .random:
            pattern_string = "random"
        case .random_runs:
            pattern_string = "randomized runs (up to array length^0.25)"
        case:
            pattern_string = "unknown (error?)"
    }

	type_string: string
	when      (DataT ==   i8) do type_string =   "i8"
	else when (DataT ==   u8) do type_string =   "u8"
	else when (DataT ==  i16) do type_string =  "i16"
	else when (DataT ==  u16) do type_string =  "u16"
	else when (DataT ==  i32) do type_string =  "i32"
	else when (DataT ==  u32) do type_string =  "u32"
	else when (DataT ==  i64) do type_string =  "i64"
	else when (DataT ==  u64) do type_string =  "u64"
	else when (DataT == i128) do type_string = "i128"
	else when (DataT == u128) do type_string = "u128"
	else when (DataT ==  int) do type_string =  "int"
	else when (DataT ==  f16) do type_string =  "f16"
	else when (DataT ==  f32) do type_string =  "f32"
	else when (DataT ==  f64) do type_string =  "f64"
	else                      do type_string =  "unknown (error?)"

	// Allow consistent or varying sets of pseudo-random numbers.
	if (seed == 0)
	{
		seed = u64(time.now()._nsec) % 64368
		fmt.printfln("Data pattern: %s. [%d]%s array, %d reps, rand() seed using time: {}.",
			pattern_string, nmemb, type_string, reps, seed)
	}
	else
	{
		fmt.printfln("Data pattern: %s. [%d]%s array, %d reps, rand() seed set to %d.",
			pattern_string, nmemb, type_string, reps, seed)
	}

    // Create initialization and working arrays
    array_init := make([dynamic]DataT, nmemb)
    array_work := make([dynamic]DataT, nmemb)
    defer delete(array_init)
    defer delete(array_work)

    slice_init : []DataT = array_init[:]
    slice_work : []DataT = array_work[:]

	// fill in initialization array with chosen data pattern
	array_initialize(slice_init, pattern, seed)

    // Initialize the working array (paranoia)
    copy_slice(slice_work, slice_init)

	// Verify
	check_array(slice_work, "Initial", 0, true, false)

	// Introduce ourselves
	fmt.printfln("%s data pattern. For each sorting method, sort an array[%d]%s.", 
		pattern_string, nmemb, type_string)

	// Confirm that all of the basic sorting algorithms do what they say on the tin.
	if (test_basic)
	{
		fmt.println("Verify correctness of basic sort calls.")

		// What's a little "O(n^2)" between friends?
		if (nmemb <= 500)
		{
			copy_slice(slice_work, slice_init)
			xsort.insertion_sort(slice_work, .ascending)
			check_array(slice_work, "  xsort.insertion_sort", 1, true, false)
			copy_slice(slice_work, slice_init)
			xsort.insertion_sort(slice_work, .descending)
			check_array(slice_work, "  xsort.insertion_sort (rev)", -1, true, false)
		}

		copy_slice(slice_work, slice_init)
		xsort.twinsort(slice_work, .ascending)
		check_array(slice_work, "  xsort.twinsort", 1, true, false)
		copy_slice(slice_work, slice_init)
		xsort.twinsort(slice_work, .descending)
		check_array(slice_work, "  xsort.twinsort (rev)", -1, true, false)

		// Unstable sorts

		if (nmemb <= 1500)  // see shell_sort() for details.
		{
			copy_slice(slice_work, slice_init)
			xsort.shell_sort(slice_work, .ascending)
			check_array(slice_work, "  xsort.shell_sort", 1, true, false)
			copy_slice(slice_work, slice_init)
			xsort.shell_sort(slice_work, .descending)
			check_array(slice_work, "  xsort.shell_sort (rev)", -1, true, false)
		}

		// Radix sort (LSD): 8- to 64-bit integers only
		when ((intrinsics.type_is_integer(DataT)) && (size_of(DataT) <= 8))
		{
			copy_slice(slice_work, slice_init)
			xsort.radix_sort_lsd(slice_work, .ascending)
			check_array(slice_work, "  xsort.radix_sort_lsd", 1, true, false)
			copy_slice(slice_work, slice_init)
			xsort.radix_sort_lsd(slice_work, .descending)
			check_array(slice_work, "  xsort.radix_sort_lsd (rev)", -1, true, false)
		}

		copy_slice(slice_work, slice_init)
		xsort.sort(slice_work, .ascending)
		check_array(slice_work, "  xsort.sort (auto choice)", 1, true, false)
		copy_slice(slice_work, slice_init)
		xsort.sort(slice_work, .descending)
		check_array(slice_work, "  xsort.sort (rev, auto choice)", -1, true, false)
	}


	// Confirm that all of the sorting algorithms with comparators do what they say on the tin.
	if (test_comparators)
	{
		// Supply a comparator for ascending (forward) sorts.
		// This works on everything. If the algorithm is stable (maintains the relative order of 
		// equal-value elements), then the sort will be stable.
		sort_ascending_stable :: proc(a, b: DataT) -> int
		{
			return (int(a > b) - int(a < b))
		}
		sort_descending_stable :: proc(a, b: DataT) -> int
		{
			return (int(a < b) - int(a > b))
		}
		/* 
			If you like sticking comparators into the sort call itself, something of the form
			xsort.insertion_sort_cmp(my_slice, 
			proc(a, b: DataT) -> int { return (int(a > b) - int(a < b)) })
			Will work and maintain stability on all xsort comparison sorts (no speed difference).
		*/

		// This is based on compare_int from core:sort, sort.odin. It also does not work with 
		// sort.quick_sort_proc(). It will give invalid results if a - (data range minimum) < b 
		// (unlikely on ints, but possible!).
		compare_dangerous :: proc(a, b: DataT) -> int {
			switch delta := a - b; {
			case delta < 0: return -1
			case delta > 0: return +1
			}
			return 0
		}
		// This is compare_u8 (or others), translated to [array datatype]. It works with everything, 
		// and seems to be just as fast as sort_ascending_stable().
		sort_ascending_alt :: proc(a, b: DataT) -> int {
			switch {
			case a < b: return -1
			case a > b: return +1
			}
			return 0
		}

		if (test_basic) do fmt.println("")
		fmt.println("Verify correctness of sort calls using comparators.")

		if (nmemb <= 500)
		{
			copy_slice(slice_work, slice_init)
			xsort.insertion_sort_cmp(slice_work, sort_ascending_stable)
			check_array(slice_work, "  xsort.insertion_sort_cmp", 1, true, false)
			copy_slice(slice_work, slice_init)
			xsort.insertion_sort_cmp(slice_work, sort_descending_stable)
			check_array(slice_work, "  xsort.insertion_sort_cmp (rev)", -1, true, false)
		}

		copy_slice(slice_work, slice_init)
		xsort.twinsort_cmp(slice_work, sort_ascending_stable)
		check_array(slice_work, "  xsort.twinsort_cmp", 1, true, false)
		copy_slice(slice_work, slice_init)
		xsort.twinsort_cmp(slice_work, sort_descending_stable)
		check_array(slice_work, "  xsort.twinsort_cmp (rev)", -1, true, false)

		copy_slice(slice_work, slice_init)
		xsort.sort_stable_cmp(slice_work, sort_ascending_stable)
		check_array(slice_work, "  xsort.sort_stable_cmp", 1, true, false)
		copy_slice(slice_work, slice_init)
		xsort.sort_stable_cmp(slice_work, sort_descending_stable)
		check_array(slice_work, "  xsort.sort_stable_cmp (rev)", -1, true, false)

		// Unstable sorts

		if (nmemb <= 1500) 
		{
			copy_slice(slice_work, slice_init)
			xsort.shell_sort_cmp(slice_work, sort_ascending_stable)
			check_array(slice_work, "  xsort.shell_sort_cmp", 1, true, false)
			copy_slice(slice_work, slice_init)
			xsort.shell_sort_cmp(slice_work, sort_descending_stable)
			check_array(slice_work, "  xsort.shell_sort_cmp (rev)", -1, true, false)
		}

		copy_slice(slice_work, slice_init)
		xsort.sort_unstable_cmp(slice_work, sort_ascending_stable)
		check_array(slice_work, "  xsort.sort_unstable_cmp (auto choice)", 1, true, false)
		copy_slice(slice_work, slice_init)
		xsort.sort_unstable_cmp(slice_work, sort_descending_stable)
		check_array(slice_work, "  xsort.sort_unstable_cmp (rev, auto choice)", -1, true, false)

		copy_slice(slice_work, slice_init)
		sort.quick_sort_proc(slice_work, sort_ascending_alt)
		check_array(slice_work, "  sort.quick_sort_proc", 1, true, false)
	}
}



// fill in initialization array with chosen data pattern
array_initialize :: proc(array_init: $A/[]$DataT, pattern: Data_Pattern, seed: u64)
{
	nmemb := len(array_init)

    // Supply a seed for the pseudo-random generator.
    rand.reset(seed)

	// Sawtooth data pattern with randomized start point. Use either a small multiplier (to allow 
	// us to check values and sums more easily as a validation step) or a large value (for data 
	// that covers the whole range of the datatype).
    if (pattern == .sawtooth || pattern == .sawtooth_small)
    {
        phase_offset := rand.float32_range(0, math.TAU)

		for i in 0 ..< nmemb
		{
			// Handle floating-point types
			when (intrinsics.type_is_float(DataT))
			{
				if (DataT == f16)
				{
					mult_f: f16 = math.F16_MAX
					if (pattern == .sawtooth_small) do mult_f /= 4

					f: f16 = math.sin_f16(f16(i) + f16(phase_offset)) * mult_f
					array_init[i] = DataT(f)
				}
				else if (DataT == f32)
				{
					mult_f: f32 = math.F32_MAX
					if (pattern == .sawtooth_small) do mult_f /= 4096

					f: f32 = math.sin_f32(f32(i) + f32(phase_offset)) * mult_f
					array_init[i] = DataT(f)
				}
				else if (DataT == f64)
				{
					mult_f: f64 = math.F64_MAX / 16 // allow verification with sums on small arrays
					if (pattern == .sawtooth_small) do mult_f /= (4096 * 4096)

					f: f64 = math.sin_f64(f64(i) + f64(phase_offset)) * mult_f
					array_init[i] = DataT(f)
				}
			}
			else // Handle integers
			{
				// Generate sign wave
				sinewave: f64 = math.sin_f64(f64(i) + f64(phase_offset))

				if (intrinsics.type_is_unsigned(DataT))
				{
					// Shift the wave
					sinewave += 1
				}

				// Multiply it by an amplitude. This is tedious in part due to type range 
				// limitations and safety checks.
				if (pattern == .sawtooth)
				{
					// Data at or below 64-bit can use the whole range. 128-bit data has to fit in an f64.
					sinewave *= (1 << (min(size_of(DataT) * 8, 64) - 1))
				}
				else
				{
					sinewave *= (1 << (min(size_of(DataT) * 6, 64) - 1))
				}

				array_init[i] = DataT(sinewave)

				// 128-bit numbers require special handling
				if ((size_of(DataT) == 16) && (pattern == .sawtooth))
				{
					array_init[i] *= math.abs(array_init[i] / 16) // allow summation on small arrays
				}
			}
		}
    }

	// Random data pattern. Options are to randomize every element (maximally disordered data), or 
	// to randomize and then run for .
	if (pattern == .random || pattern == .random_runs)
	{
		// Use length-adjusted runs of random numbers.
		run_max := 1
		if (pattern == .random_runs)
		{
			run_max += int(math.pow_f32(f32(nmemb), 0.25))
		}

		// Fill our intialization array (we assign to i below)
		for i := 0; i < nmemb; i += 1
		{
			min, max: DataT

			// Handle floating-point types.
			when (intrinsics.type_is_float(DataT))
			{
				when (DataT == f16)
				{
					min = math.F16_MIN
					max = math.F16_MAX
					array_init[i] = DataT(rand.float32_range(f32(min), f32(max)))
				}
				else when (DataT == f32)
				{
					min = math.F32_MIN
					max = math.F32_MAX
					array_init[i] = DataT(rand.float32_range(min, max))
				}
				else when (DataT == f64)
				{
					min = math.F64_MIN / 16 // allow verification with sums on small arrays
					max = math.F64_MAX / 16
					array_init[i] = DataT(rand.float64_range(min, max))
				}
			}
			else // Handle signed and unsigned integer types (up to 128-bit)
			{
				// Reduce data range somewhat
				data_range : u32 = size_of(DataT) * 7
				when (!intrinsics.type_is_unsigned(DataT))
				{
					min = -(1 << (data_range - 1))
					max =  (1 << (data_range - 1)) - 1
					array_init[i] = DataT(rand.int128_range(i128(min), i128(max)))
				}
				else
				{
					min = 0
					max = (1 << (data_range)) - 1
					array_init[i] = DataT(rand.uint128_range(u128(min), u128(max)))
				}
			}

			// Allow runs of identical data; cut run short at end of array
			if (pattern == .random_runs)
			{
				run := rand.int_range(1, run_max)
				for j in 1 ..< run
				{
					if (i >= nmemb - 1) do break
					array_init[i + 1] = array_init[i]
					i += 1
				}
			}
		}
	}
}


/*
 * Verify correctness. Options to check sorting forward (check_sort > 0) or backwards (<0); to check 
 * sums; and/or display a printout of the array.
 */
check_array :: proc(array_work: []$DataT, label: string, check_sort: int, check_sum: bool, 
	printout: bool)
{
	nmemb := len(array_work)
	error := 0

	// Sums: expect imprecision or errors with large datatypes and with large arrays
	if (check_sum)
	{
		if (intrinsics.type_is_integer(DataT))
		{
			sum_i : i128 = 0
			for i in 0 ..< nmemb do sum_i += i128(array_work[i])
			fmt.printfln("{}: Sum is {}.  ", label, sum_i)
		}
		else if (intrinsics.type_is_float(DataT))
		{
			sum_f : f64 = 0
			for i in 0 ..< nmemb do sum_f += f64(array_work[i])
			fmt.printfln("{}: Sum is {}.  ", label, sum_f)
		}
	}

	if (check_sort != 0)
	{
		if (intrinsics.type_is_comparable(DataT))
		{
			if (check_sort > 0)
			{
				scan_array1: for i in 1 ..< nmemb
				{
					if (array_work[i] < array_work[i-1]) 
					{
						fmt.printfln("Sorting error at [{}]", i)
						error += 1
						if (error >= 4) do break scan_array1 // don't spam
					}
				}
			}
			else
			{
				scan_array2: for i in 1 ..< nmemb
				{
					if (array_work[i] > array_work[i-1]) 
					{
						fmt.printfln("Sorting error at [{}]", i)
						error += 1
						if (error >= 4) do break scan_array2 // don't spam
					}
				}
			}
			if (error == 0) do fmt.printfln("None out of order.")
		}
		else
		{
			fmt.println("Check sort error: Array type is non-comparable.")
		}
	}
	if (printout)
	{
		if ((check_sort == 0) && (!check_sum)) do fmt.printfln("{}:", label)

		if (nmemb <= 16)
		{
			fmt.printfln("{}", array_work)
		}
		else
		{
			scan_front := 4
			scan_rear := 4
			scan_middle := 8
			fmt.printfln("{}, {}, {}, {} ...", 
				array_work[0], array_work[1], array_work[2], array_work[3])
			
			count := 0
			for i := nmemb / 2 - 4; count < 4; i += 1
			{
				if count < 3 do fmt.printf("{}, ", array_work[i])
				else         do fmt.printf("{}\n", array_work[i])
				count += 1
			}
			for i := nmemb / 2; count < 8; i += 1
			{
				if count < 7 do fmt.printf("{}, ", array_work[i])
				else         do fmt.printf("{} ...\n", array_work[i])
				count += 1
			}

			fmt.printfln("{}, {}, {}, {}", 
				array_work[nmemb - 4], array_work[nmemb - 3], array_work[nmemb - 2], array_work[nmemb - 1])
		}
	}
}