/*
 * Date: Mar 2026, being the 6513th penta-femtofortnight of American independence.
 * Author: Alexander M. Swift
 *
 * Do some benchmarking of the xsort basic and comparator sorting calls. This is the file we use to 
 * tune the auto-selection sorts on arrays of numbers.
 * Demonstrate the flexibility - and also, sometimes, the speed penalties - of sorts with auto-
 * selection of algorithm and method.
 */

package main

import "base:intrinsics"

import "core:fmt"
import "core:math"
import "core:math/rand"
import "core:mem" // for tracking allocator
import "core:os"
import "core:sort"
import strconv "core:strconv"
import "core:time"

import "xsort"


/*
 * The contents of this file are Copyright (C) The xsort package author(s). They are released under 
 * the terms of the MIT license, or to the public domain, your choice.
 */

Data_Pattern :: enum
{
    sawtooth          = 0, // Sawtooth (alternately locally sorted and reverse-sorted) generated by a sine wave.
    sawtooth_small    = 1, // Same, with limited data range, suitable for verification
	random            = 2, // Completely random (maximum disorder)
	random_runs       = 3, // Random, then run of equal values up to (length of array^0.25).
}

/*
 * Performs basic benchmarking on arrays of numbers.
 * Useful parameters are length of array, reps, data pattern (see Data_Pattern), and random seed.
 *
 * Verify and benchmark sorting algorithms ported to Odin in the xsort package; compare with 
 * Odin's quick_sort on arrays of numbers. This is not intended to be even remotely a rigorous 
 * micro-benchmarking exercise: safety - specifically, type and array memory space safety - and 
 * correctness are the primary goals.
 *
 * We treat stable and unstable sorts as equals here, as we're just sorting numbers without 
 * additional information attached to them. This changes when we later turn to sorts on arrays of 
 * structs, structs of arrays, and index searches.
 *
 * Note on benchmarking: The time.now and time.since method used below is usually fine-grained 
 * enough for our purposes. However, if procedure calls take very little time (such as an insertion 
 * sort on an array with 4 elements), estimates of time elapsed get inflated. Sometimes by a lot. 
 * The time.stopwatch method is a bit less subject to this, but the improvement is not great. 
 * It took me a bit to realize that Odin is NOT five times slower than C in in this particular case...
 * However, I am not still sure of how to match C's timespec_get(&ts1, TIME_UTC) precision on small
 * durations.
 * -AMS-
 */
main :: proc() 
{
	debug_mem := false
	if (debug_mem)
	{
		// Initialize and use Odin's tracking allocator
		track: mem.Tracking_Allocator
		mem.tracking_allocator_init(&track, context.allocator)
		context.allocator = mem.tracking_allocator(&track)

		// Printout memory leaks on main() end.
		defer {
			if len(track.allocation_map) > 0 {
				fmt.eprintf("=== %v allocations not freed: ===\n", len(track.allocation_map))
				for _, entry in track.allocation_map {
					fmt.eprintf("- %v bytes @ %v\n", entry.size, entry.location)
				}
			}
			else
			{
				fmt.eprint("Tracking allocator: no memory leaks detected.")
			}
			mem.tracking_allocator_destroy(&track)
		}
	}


	// Basic: sorts without comparators. Comparators: custom comparison procedures.
	test_basic := true
	test_comparators := true

    // Default test parameters
	// DataT: must be one of: i8, u8, i16, u16, i32, u32, i64, u64, i128, u128,
	// (or their equivalents, such as int). This has to be specified at compile time.
	DataT :: int

	// nmemb, reps: larger arrays don't just (usually) require more computations per element to sort, they 
	// also are more likely to be stored in slower memory caches.
    nmemb: int = 20
    reps: int = 1

	// Data pattern has to at least roughly match the use-case for benchmarking to be useful.
    pattern: Data_Pattern = .sawtooth

	// Varying the seed, especially for sawtooth data, can make a large difference to run time 
	// for some data patterns on small arrays, because how well-sorted such an input array already 
	// is will vary.
    seed: u64 = 42 // We know the answer ... but do we know the question?

    ok: bool
    val, i, j: int

	// Require that our data type be a number
	if (!intrinsics.type_is_numeric(DataT))
	{
		fmt.printfln("Requested array type is non-numeric. Quitting.")
		return
	}

    // Accept command-line arguments to modify test parameters
    for i in 1 ..< len(os.args)
    {
        switch i 
        {
            case 1:
                nmemb, ok = strconv.parse_int(os.args[1]); assert(ok)
            case 2:
                reps, ok = strconv.parse_int(os.args[2]); assert(ok)
            case 3:
            {
                val, ok = strconv.parse_int(os.args[3]); assert(ok)
                pattern = cast(Data_Pattern)val
            }
            case 4:
            {
                seed, ok = strconv.parse_u64(os.args[4]); assert(ok)
            }
        }
    }

    // Describe the test parameters
    pattern_string : string
    switch pattern
    {
        case .sawtooth:
            pattern_string = "sinewave sawtooth"
        case .sawtooth_small:
            pattern_string = "sinewave sawtooth, small range"
        case .random:
            pattern_string = "random"
        case .random_runs:
            pattern_string = "random, with runs (up to array length^0.25)"
        case:
            pattern_string = "unknown (error?)"
    }

	type_string: string
	when      (DataT ==   i8) do type_string =   "i8"
	else when (DataT ==   u8) do type_string =   "u8"
	else when (DataT ==  i16) do type_string =  "i16"
	else when (DataT ==  u16) do type_string =  "u16"
	else when (DataT ==  i32) do type_string =  "i32"
	else when (DataT ==  u32) do type_string =  "u32"
	else when (DataT ==  i64) do type_string =  "i64"
	else when (DataT ==  u64) do type_string =  "u64"
	else when (DataT == i128) do type_string = "i128"
	else when (DataT == u128) do type_string = "u128"
	else when (DataT ==  int) do type_string =  "int"
	else when (DataT ==  f16) do type_string =  "f16"
	else when (DataT ==  f32) do type_string =  "f32"
	else when (DataT ==  f64) do type_string =  "f64"
	else                      do type_string =  "unknown (error?)"

	// Allow consistent or varying sets of pseudo-random numbers.
	if (seed == 0)
	{
		seed = u64(time.now()._nsec) % 64368
		fmt.printfln("Data pattern: %s. [%d]%s array, %d reps, rand() seed using time: {}.",
			pattern_string, nmemb, type_string, reps, seed)
	}
	else
	{
		fmt.printfln("Data pattern: %s. [%d]%s array, %d reps, rand() seed set to %d.",
			pattern_string, nmemb, type_string, reps, seed)
	}

    // Create initialization and working arrays
    array_init := make([dynamic]DataT, nmemb)
    array_work := make([dynamic]DataT, nmemb)
    defer delete(array_init)
    defer delete(array_work)

    slice_init : []DataT = array_init[:]
    slice_work : []DataT = array_work[:]

	// fill in initialization array with chosen data pattern
	array_initialize(slice_init, pattern, seed)

    // Initialize the working array (paranoia)
    copy_slice(slice_work, slice_init)

	// Set up timers
	start : time.Time
	duration_insertion : time.Duration = 0
	duration_insertion2 : time.Duration = 0
	duration_twin : time.Duration = 0
	duration_shell : time.Duration = 0
	duration_radix_lsd : time.Duration = 0
	duration_xsort_sort_stable : time.Duration = 0
	duration_xsort_sort_unstable : time.Duration = 0

	duration_sort_merge : time.Duration = 0
	duration_sort_sort : time.Duration = 0
	duration_sort_quicksort : time.Duration = 0
	duration_slice_sort_by : time.Duration = 0

	/*
	 * Comments on benchmark times (following up on the procedure notes):
	 * Timings on these benchmarks will always vary. If a sort call takes any significant time, 
	 * timings appear to be accurate and the imprecision is fine for basic stuff like we're doing.
	 * However, an efficient algorithim (like insertion sort) on a small (< ~15 element) array takes
	 * considerably less time than than will be reported - sometimes several times less. 
	 *
	 * So, if you need accurate relative values on small arrays, then multiply 
	 * the number of sort calls (and, necessarily, the array reinitializations, which apparently are 
	 * really fast).
	 */

	// Introduce ourselves
	fmt.printfln("%d reps, %s data pattern. For each sorting method, each rep sorts an array[%d]%s in ascending order.", 
		reps, pattern_string, nmemb, type_string)
	
	// Warm-up ("We're using THIS data a bunch, memory-manager."). Without a warm-up, the first test 
	// is often slower than the rest.
	for r in 0 ..< 1 + reps / 10
	{
		copy_slice(slice_work, slice_init)
		xsort.twinsort(slice_work, .ascending) // doesn't seem to affect this procedure's timings.
	}

	// Perform basic benchmarking
	if (test_basic)
	{
		loop_start := time.now()
		for r in 0 ..< reps
		{
			if (nmemb <= 250)
			{
				start = time.now()
				copy_slice(slice_work, slice_init)
				xsort.insertion_sort(slice_work, .ascending)
				copy_slice(slice_work, slice_init)
				xsort.insertion_sort(slice_work, .ascending)
				copy_slice(slice_work, slice_init)
				xsort.insertion_sort(slice_work, .ascending)
				copy_slice(slice_work, slice_init)
				xsort.insertion_sort(slice_work, .ascending)
				copy_slice(slice_work, slice_init)
				xsort.insertion_sort(slice_work, .ascending)
				copy_slice(slice_work, slice_init)
				xsort.insertion_sort(slice_work, .ascending)
				copy_slice(slice_work, slice_init)
				xsort.insertion_sort(slice_work, .ascending)
				copy_slice(slice_work, slice_init)
				xsort.insertion_sort(slice_work, .ascending)
				copy_slice(slice_work, slice_init)
				xsort.insertion_sort(slice_work, .ascending)
				copy_slice(slice_work, slice_init)
				xsort.insertion_sort(slice_work, .ascending)
				duration_insertion += time.since(start)
			}

			start = time.now()
			copy_slice(slice_work, slice_init)
			xsort.twinsort(slice_work, .ascending)
			copy_slice(slice_work, slice_init)
			xsort.twinsort(slice_work, .ascending)
			copy_slice(slice_work, slice_init)
			xsort.twinsort(slice_work, .ascending)
			copy_slice(slice_work, slice_init)
			xsort.twinsort(slice_work, .ascending)
			copy_slice(slice_work, slice_init)
			xsort.twinsort(slice_work, .ascending)
			copy_slice(slice_work, slice_init)
			xsort.twinsort(slice_work, .ascending)
			copy_slice(slice_work, slice_init)
			xsort.twinsort(slice_work, .ascending)
			copy_slice(slice_work, slice_init)
			xsort.twinsort(slice_work, .ascending)
			copy_slice(slice_work, slice_init)
			xsort.twinsort(slice_work, .ascending)
			copy_slice(slice_work, slice_init)
			xsort.twinsort(slice_work, .ascending)
			duration_twin += time.since(start)

			// Scales very poorly
			// if (nmemb <= 2500)
			// {
			// 	start = time.now()
			// 	copy_slice(slice_work, slice_init)
			// 	sort.merge_sort(slice_work)
			// 	copy_slice(slice_work, slice_init)
			// 	sort.merge_sort(slice_work)
			// 	copy_slice(slice_work, slice_init)
			// 	sort.merge_sort(slice_work)
			// 	copy_slice(slice_work, slice_init)
			// 	sort.merge_sort(slice_work)
			// 	copy_slice(slice_work, slice_init)
			// 	sort.merge_sort(slice_work)
			// 	copy_slice(slice_work, slice_init)
			// 	sort.merge_sort(slice_work)
			// 	copy_slice(slice_work, slice_init)
			// 	sort.merge_sort(slice_work)
			// 	copy_slice(slice_work, slice_init)
			// 	sort.merge_sort(slice_work)
			// 	copy_slice(slice_work, slice_init)
			// 	sort.merge_sort(slice_work)
			// 	copy_slice(slice_work, slice_init)
			// 	sort.merge_sort(slice_work)
			// 	duration_sort_merge += time.since(start)
			// }

			if (nmemb <= 1500) // see shell_sort()
			{
				start = time.now()
				copy_slice(slice_work, slice_init)
				xsort.shell_sort(slice_work, .ascending)
				copy_slice(slice_work, slice_init)
				xsort.shell_sort(slice_work, .ascending)
				copy_slice(slice_work, slice_init)
				xsort.shell_sort(slice_work, .ascending)
				copy_slice(slice_work, slice_init)
				xsort.shell_sort(slice_work, .ascending)
				copy_slice(slice_work, slice_init)
				xsort.shell_sort(slice_work, .ascending)
				copy_slice(slice_work, slice_init)
				xsort.shell_sort(slice_work, .ascending)
				copy_slice(slice_work, slice_init)
				xsort.shell_sort(slice_work, .ascending)
				copy_slice(slice_work, slice_init)
				xsort.shell_sort(slice_work, .ascending)
				copy_slice(slice_work, slice_init)
				xsort.shell_sort(slice_work, .ascending)
				copy_slice(slice_work, slice_init)
				xsort.shell_sort(slice_work, .ascending)
				duration_shell += time.since(start)
			}

			// // Radix sort (LSD): 8- to 64-bit integers only; very slow on ints, 64-bits
			// when ((intrinsics.type_is_integer(DataT)) && (size_of(DataT) <= 8))
			// {
			// 	if (nmemb >= 20) // Radix sort has some overhead; don't try running 5m x [4]int...
			// 	{
			// 		start = time.now()
			// 		copy_slice(slice_work, slice_init)
			// 		xsort.radix_sort_lsd(slice_work, .ascending)
			// 		copy_slice(slice_work, slice_init)
			// 		xsort.radix_sort_lsd(slice_work, .ascending)
			// 		copy_slice(slice_work, slice_init)
			// 		xsort.radix_sort_lsd(slice_work, .ascending)
			// 		copy_slice(slice_work, slice_init)
			// 		xsort.radix_sort_lsd(slice_work, .ascending)
			// 		copy_slice(slice_work, slice_init)
			// 		xsort.radix_sort_lsd(slice_work, .ascending)
			// 		copy_slice(slice_work, slice_init)
			// 		xsort.radix_sort_lsd(slice_work, .ascending)
			// 		copy_slice(slice_work, slice_init)
			// 		xsort.radix_sort_lsd(slice_work, .ascending)
			// 		copy_slice(slice_work, slice_init)
			// 		xsort.radix_sort_lsd(slice_work, .ascending)
			// 		copy_slice(slice_work, slice_init)
			// 		xsort.radix_sort_lsd(slice_work, .ascending)
			// 		copy_slice(slice_work, slice_init)
			// 		xsort.radix_sort_lsd(slice_work, .ascending)
			// 		duration_radix_lsd += time.since(start)
			// 	}
			// }

			start = time.now()
			copy_slice(slice_work, slice_init)
			xsort.sort(slice_work, .ascending)
			copy_slice(slice_work, slice_init)
			xsort.sort(slice_work, .ascending)
			copy_slice(slice_work, slice_init)
			xsort.sort(slice_work, .ascending)
			copy_slice(slice_work, slice_init)
			xsort.sort(slice_work, .ascending)
			copy_slice(slice_work, slice_init)
			xsort.sort(slice_work, .ascending)
			copy_slice(slice_work, slice_init)
			xsort.sort(slice_work, .ascending)
			copy_slice(slice_work, slice_init)
			xsort.sort(slice_work, .ascending)
			copy_slice(slice_work, slice_init)
			xsort.sort(slice_work, .ascending)
			copy_slice(slice_work, slice_init)
			xsort.sort(slice_work, .ascending)
			copy_slice(slice_work, slice_init)
			xsort.sort(slice_work, .ascending)
			duration_xsort_sort_unstable += time.since(start)

			// Select core library functions

			// Slow. Not sure why.
			// start = time.now()
			// copy_slice(slice_work, slice_init)
			// sort.sort(sort.slice_interface(&slice_work))
			// duration_sort_sort += time.since(start)

			// Very fast.
			start = time.now()
			copy_slice(slice_work, slice_init)
			sort.quick_sort(slice_work)
			copy_slice(slice_work, slice_init)
			sort.quick_sort(slice_work)
			copy_slice(slice_work, slice_init)
			sort.quick_sort(slice_work)
			copy_slice(slice_work, slice_init)
			sort.quick_sort(slice_work)
			copy_slice(slice_work, slice_init)
			sort.quick_sort(slice_work)
			copy_slice(slice_work, slice_init)
			sort.quick_sort(slice_work)
			copy_slice(slice_work, slice_init)
			sort.quick_sort(slice_work)
			copy_slice(slice_work, slice_init)
			sort.quick_sort(slice_work)
			copy_slice(slice_work, slice_init)
			sort.quick_sort(slice_work)
			copy_slice(slice_work, slice_init)
			sort.quick_sort(slice_work)
			duration_sort_quicksort += time.since(start)

			// Smoothsort. Not competitve with quicksort.
			// start = time.now()
			// copy_slice(slice_work, slice_init)
			// slice.sort_by(slice_work, 
			// 	proc(a, b: DataT) -> bool { return a < b })
			// duration_slice_sort_by += time.since(start)

			// "I'm working, I swear!"
			loop_time_elapsed := time.duration_seconds(time.since(loop_start))
			if (loop_time_elapsed >= 5)
			{
				fmt.printfln("rep %d of %d", r, reps)
				loop_start = time.now()
			}
		}

		// Results
		fmt.println("Basic sorts:")
		fmt.printfln("  Stable:")
		if (duration_insertion > 0)
		{
			fmt.printfln("    xsort.insertion_sort: %.0f msec.", 
			time.duration_milliseconds(duration_insertion))
		}
		if (duration_insertion2 > 0)
		{
			fmt.printfln("    xsort.insertion_sort, #2: %.0f msec.", 
			time.duration_milliseconds(duration_insertion2))
		}
		if (duration_twin > 0)
		{
			fmt.printfln("    xsort.twinsort: %.0f msec.", 
				time.duration_milliseconds(duration_twin))
		}
		if (duration_xsort_sort_stable > 0)
		{
			fmt.printfln("    xsort.sort_stable: %.0f msec.", 
				time.duration_milliseconds(duration_xsort_sort_stable))
		}
		if (duration_sort_merge > 0)
		{
			fmt.printfln("    sort.merge_sort: %.0f msec.", 
				time.duration_milliseconds(duration_sort_merge))
		}

		fmt.printfln("  Unstable:")
		if (duration_shell > 0)
		{
			fmt.printfln("    xsort.shell_sort: %.0f msec.", 
				time.duration_milliseconds(duration_shell))
		}
		if (duration_radix_lsd > 0)
		{
			fmt.printfln("    xsort.radix_sort: %.0f msec.", 
				time.duration_milliseconds(duration_radix_lsd))
		}
		if (duration_xsort_sort_unstable > 0)
		{
			fmt.printfln("    xsort.sort: %.0f msec.", 
				time.duration_milliseconds(duration_xsort_sort_unstable))
		}
		if (duration_sort_sort > 0)
		{
			fmt.printfln("    sort.sort: %.0f msec.", 
				time.duration_milliseconds(duration_sort_sort))
		}
		if (duration_sort_quicksort > 0)
		{
			fmt.printfln("    sort.quick_sort: %.0f msec.", 
				time.duration_milliseconds(duration_sort_quicksort))
		}
		// if (duration_slice_sort_by > 0)
		// {
		// 	fmt.printfln("  slice.sort_by (smoothsort): %.0f msec.", 
		// 		time.duration_milliseconds(duration_slice_sort_by))
		// }
	}

	duration_insertion = 0
	duration_twin = 0
	duration_shell = 0
	duration_radix_lsd = 0
	duration_xsort_sort_stable = 0
	duration_xsort_sort_unstable = 0

	duration_sort_merge = 0
	duration_sort_quicksort = 0
	duration_sort_sort = 0
	duration_slice_sort_by = 0

	// Perform basic benchmarking
	if (test_comparators)
	{
		// See comments on comparators in test #1.
		sort_ascending_stable :: proc(a, b: DataT) -> int
		{
			return (int(a > b) - int(a < b))
		}
		// This does not seem to be any faster? (unexpected...)
		// (doesn't work with sort.quick_sort_proc())
		sort_ascending_unstable :: proc(a, b: DataT) -> int
		{
			return (a > b) ? 1 : 0
		}
		sort_ascending_alt :: proc(a, b: DataT) -> int {
			switch {
			case a < b: return -1
			case a > b: return +1
			}
			return 0
		}

		if (test_basic) do fmt.println("")
		loop_start := time.now()

		for r in 0 ..< reps
		{
			if (nmemb <= 250)
			{
				start = time.now()
				copy_slice(slice_work, slice_init)
				xsort.insertion_sort_cmp(slice_work, sort_ascending_stable)
				copy_slice(slice_work, slice_init)
				xsort.insertion_sort_cmp(slice_work, sort_ascending_stable)
				copy_slice(slice_work, slice_init)
				xsort.insertion_sort_cmp(slice_work, sort_ascending_stable)
				copy_slice(slice_work, slice_init)
				xsort.insertion_sort_cmp(slice_work, sort_ascending_stable)
				copy_slice(slice_work, slice_init)
				xsort.insertion_sort_cmp(slice_work, sort_ascending_stable)
				copy_slice(slice_work, slice_init)
				xsort.insertion_sort_cmp(slice_work, sort_ascending_stable)
				copy_slice(slice_work, slice_init)
				xsort.insertion_sort_cmp(slice_work, sort_ascending_stable)
				copy_slice(slice_work, slice_init)
				xsort.insertion_sort_cmp(slice_work, sort_ascending_stable)
				copy_slice(slice_work, slice_init)
				xsort.insertion_sort_cmp(slice_work, sort_ascending_stable)
				copy_slice(slice_work, slice_init)
				xsort.insertion_sort_cmp(slice_work, sort_ascending_stable)
				duration_insertion += time.since(start)
			}

			start = time.now()
			copy_slice(slice_work, slice_init)
			xsort.twinsort_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.twinsort_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.twinsort_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.twinsort_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.twinsort_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.twinsort_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.twinsort_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.twinsort_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.twinsort_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.twinsort_cmp(slice_work, sort_ascending_stable)
			duration_twin += time.since(start)

			start = time.now()
			copy_slice(slice_work, slice_init)
			xsort.sort_stable_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.sort_stable_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.sort_stable_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.sort_stable_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.sort_stable_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.sort_stable_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.sort_stable_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.sort_stable_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.sort_stable_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.sort_stable_cmp(slice_work, sort_ascending_stable)
			duration_xsort_sort_stable += time.since(start)

			// if (nmemb <= 2500)
			// {
			// 	copy_slice(slice_work, slice_init)
			// 	start = time.now()
			// 	sort.merge_sort_proc(slice_work, sort_ascending_universal)
			// 	duration_sort_merge += time.since(start)
			// }

			if (nmemb <= 1500) // see shell_sort()
			{
				start = time.now()
				copy_slice(slice_work, slice_init)
				xsort.shell_sort_cmp(slice_work, sort_ascending_stable)
				copy_slice(slice_work, slice_init)
				xsort.shell_sort_cmp(slice_work, sort_ascending_stable)
				copy_slice(slice_work, slice_init)
				xsort.shell_sort_cmp(slice_work, sort_ascending_stable)
				copy_slice(slice_work, slice_init)
				xsort.shell_sort_cmp(slice_work, sort_ascending_stable)
				copy_slice(slice_work, slice_init)
				xsort.shell_sort_cmp(slice_work, sort_ascending_stable)
				copy_slice(slice_work, slice_init)
				xsort.shell_sort_cmp(slice_work, sort_ascending_stable)
				copy_slice(slice_work, slice_init)
				xsort.shell_sort_cmp(slice_work, sort_ascending_stable)
				copy_slice(slice_work, slice_init)
				xsort.shell_sort_cmp(slice_work, sort_ascending_stable)
				copy_slice(slice_work, slice_init)
				xsort.shell_sort_cmp(slice_work, sort_ascending_stable)
				copy_slice(slice_work, slice_init)
				xsort.shell_sort_cmp(slice_work, sort_ascending_stable)
				duration_shell += time.since(start)
			}

			start = time.now()
			copy_slice(slice_work, slice_init)
			xsort.sort_unstable_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.sort_unstable_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.sort_unstable_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.sort_unstable_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.sort_unstable_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.sort_unstable_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.sort_unstable_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.sort_unstable_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.sort_unstable_cmp(slice_work, sort_ascending_stable)
			copy_slice(slice_work, slice_init)
			xsort.sort_unstable_cmp(slice_work, sort_ascending_stable)
			duration_xsort_sort_unstable += time.since(start)

			start = time.now()
			copy_slice(slice_work, slice_init)
			sort.quick_sort_proc(slice_work, sort_ascending_alt)
			copy_slice(slice_work, slice_init)
			sort.quick_sort_proc(slice_work, sort_ascending_alt)
			copy_slice(slice_work, slice_init)
			sort.quick_sort_proc(slice_work, sort_ascending_alt)
			copy_slice(slice_work, slice_init)
			sort.quick_sort_proc(slice_work, sort_ascending_alt)
			copy_slice(slice_work, slice_init)
			sort.quick_sort_proc(slice_work, sort_ascending_alt)
			copy_slice(slice_work, slice_init)
			sort.quick_sort_proc(slice_work, sort_ascending_alt)
			copy_slice(slice_work, slice_init)
			sort.quick_sort_proc(slice_work, sort_ascending_alt)
			copy_slice(slice_work, slice_init)
			sort.quick_sort_proc(slice_work, sort_ascending_alt)
			copy_slice(slice_work, slice_init)
			sort.quick_sort_proc(slice_work, sort_ascending_alt)
			copy_slice(slice_work, slice_init)
			sort.quick_sort_proc(slice_work, sort_ascending_alt)
			duration_sort_quicksort += time.since(start)

			// copy_slice(slice_work, slice_init)
			// start = time.now()
			// slice.sort_by(slice_work, proc(a, b: DataT) -> bool { return a < b }) // Why you have to be special?
			// duration_slice_sort_by += time.since(start)

			// "I was just resting my eyes."
			loop_time_elapsed := time.duration_seconds(time.since(loop_start))
			if (loop_time_elapsed >= 5)
			{
				fmt.printfln("rep %d of %d", r, reps)
				loop_start = time.now()
			}
		}

		// Results
		fmt.println("Custom sorts:")
		fmt.println("  Stable:")
		if (duration_insertion > 0)
		{
			fmt.printfln("    xsort.insertion_sort_cmp: %.0f msec.", 
			time.duration_milliseconds(duration_insertion))
		}
		if (duration_twin > 0)
		{
			fmt.printfln("    xsort.twinsort_cmp: %.0f msec.", 
				time.duration_milliseconds(duration_twin))
		}
		if (duration_xsort_sort_stable > 0)
		{
			fmt.printfln("    xsort.sort_stable_cmp: %.0f msec.", 
				time.duration_milliseconds(duration_xsort_sort_stable))
		}
		if (duration_sort_merge > 0)
		{
			fmt.printfln("    sort.merge_sort_proc: %.0f msec.", 
				time.duration_milliseconds(duration_sort_merge))
		}

		fmt.printfln("  Unstable:")
		if (duration_shell > 0)
		{
			fmt.printfln("    xsort.shell_sort_cmp: %.0f msec.", 
				time.duration_milliseconds(duration_shell))
		}
		if (duration_xsort_sort_unstable > 0)
		{
			fmt.printfln("    xsort.sort_unstable_cmp: %.0f msec.", 
				time.duration_milliseconds(duration_xsort_sort_unstable))
		}
		if (duration_sort_quicksort > 0)
		{
			fmt.printfln("    sort.quick_sort_proc: %.0f msec.", 
				time.duration_milliseconds(duration_sort_quicksort))
		}
		if (duration_slice_sort_by > 0)
		{
			fmt.printfln("    slice.sort_by: %.0f msec.", 
				time.duration_milliseconds(duration_slice_sort_by))
		}
	}
}



// fill in initialization array with chosen data pattern
array_initialize :: proc(array_init: $A/[]$DataT, pattern: Data_Pattern, seed: u64)
{
	nmemb := len(array_init)

    // Supply a seed for the pseudo-random generator.
    rand.reset(seed)

	// Sawtooth data pattern with randomized start point. Use either a small multiplier (to allow 
	// us to check values and sums more easily as a validation step) or a large value (for data 
	// that covers the whole range of the datatype).
    if (pattern == .sawtooth || pattern == .sawtooth_small)
    {
        phase_offset := rand.float32_range(0, math.TAU)

		for i in 0 ..< nmemb
		{
			// Handle floating-point types
			when (intrinsics.type_is_float(DataT))
			{
				if (DataT == f16)
				{
					mult_f: f16 = math.F16_MAX
					if (pattern == .sawtooth_small) do mult_f /= 4

					f: f16 = math.sin_f16(f16(i) + f16(phase_offset)) * mult_f
					array_init[i] = DataT(f)
				}
				else if (DataT == f32)
				{
					mult_f: f32 = math.F32_MAX
					if (pattern == .sawtooth_small) do mult_f /= 4096

					f: f32 = math.sin_f32(f32(i) + f32(phase_offset)) * mult_f
					array_init[i] = DataT(f)
				}
				else if (DataT == f64)
				{
					mult_f: f64 = math.F64_MAX / 16 // allow verification with sums on small arrays
					if (pattern == .sawtooth_small) do mult_f /= (4096 * 4096)

					f: f64 = math.sin_f64(f64(i) + f64(phase_offset)) * mult_f
					array_init[i] = DataT(f)
				}
			}
			else // Handle integers
			{
				// Generate sign wave
				sinewave: f64 = math.sin_f64(f64(i) + f64(phase_offset))

				if (intrinsics.type_is_unsigned(DataT))
				{
					// Shift the wave
					sinewave += 1
				}

				// Multiply it by an amplitude. This is tedious in part due to type range 
				// limitations and safety checks.
				if (pattern == .sawtooth)
				{
					// Data at or below 64-bit can use the whole range. 128-bit data has to fit in an f64.
					sinewave *= (1 << (min(size_of(DataT) * 8, 64) - 1))
				}
				else
				{
					sinewave *= (1 << (min(size_of(DataT) * 6, 64) - 1))
				}

				array_init[i] = DataT(sinewave)

				// 128-bit numbers require special handling
				if ((size_of(DataT) == 16) && (pattern == .sawtooth))
				{
					array_init[i] *= math.abs(array_init[i] / 16) // allow summation on small arrays
				}
			}
		}
    }

	// Random data pattern. Options are to randomize every element (maximally disordered data), or 
	// to randomize and then run for .
	if (pattern == .random || pattern == .random_runs)
	{
		// Use length-adjusted runs of random numbers.
		run_max := 1
		if (pattern == .random_runs)
		{
			run_max += int(math.pow_f32(f32(nmemb), 0.25))
		}

		// Fill our intialization array (we assign to i below)
		for i := 0; i < nmemb; i += 1
		{
			min, max: DataT

			// Handle floating-point types.
			when (intrinsics.type_is_float(DataT))
			{
				when (DataT == f16)
				{
					min = math.F16_MIN
					max = math.F16_MAX
					array_init[i] = DataT(rand.float32_range(f32(min), f32(max)))
				}
				else when (DataT == f32)
				{
					min = math.F32_MIN
					max = math.F32_MAX
					array_init[i] = DataT(rand.float32_range(min, max))
				}
				else when (DataT == f64)
				{
					min = math.F64_MIN / 16 // allow verification with sums on small arrays
					max = math.F64_MAX / 16
					array_init[i] = DataT(rand.float64_range(min, max))
				}
			}
			else // Handle signed and unsigned integer types (up to 128-bit)
			{
				// Reduce data range somewhat
				data_range : u32 = size_of(DataT) * 7
				when (!intrinsics.type_is_unsigned(DataT))
				{
					min = -(1 << (data_range - 1))
					max =  (1 << (data_range - 1)) - 1
					array_init[i] = DataT(rand.int128_range(i128(min), i128(max)))
				}
				else
				{
					min = 0
					max = (1 << (data_range)) - 1
					array_init[i] = DataT(rand.uint128_range(u128(min), u128(max)))
				}
			}

			// Allow runs of identical data; cut run short at end of array
			if (pattern == .random_runs)
			{
				run := rand.int_range(1, run_max)
				for j in 1 ..< run
				{
					if (i >= nmemb - 1) do break
					array_init[i + 1] = array_init[i]
					i += 1
				}
			}
		}
	}
}
